services:
  - type: web
    name: school-management-backend
    runtime: python

    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput

    startCommand: |
      gunicorn core.wsgi:application

    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10

      - key: DEBUG
        value: "False"

      - key: DJANGO_SECRET_KEY
        generateValue: true

      - key: DATABASE_URL
        fromDatabase:
          name: school-management-db
          property: connectionString

databases:
  - name: school-management-db