# Generated by Django 6.0.7 on 2026-08-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_attendance_marks'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'date'), name='unique_student_date'),
        ),
        migrations.AddConstraint(
            model_name='marks',
            constraint=models.UniqueConstraint(fields=('student', 'subject'), name='unique_student_subject'),
        ),
    ]
